apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: AgentEndpoint
metadata:
  name: danske-spil-gambler-internal
  namespace: danske-spil
spec:
  url: http://danske-spil-gambler.internal:80
  bindings:
    - internal
  upstream:
    protocol: http1
    url: http://gambler-api.danske-spil:8080
---
apiVersion: ngrok.k8s.ngrok.com/v1alpha1
kind: AgentEndpoint
metadata:
  name: saxo-daytrader-internal
  namespace: saxo-rust
spec:
  url: http://saxo-daytrader.internal:80
  bindings:
    - internal
  upstream:
    protocol: http1
    url: http://daytrader-frontend.saxo-rust:8000
